export const GET_BOOKING_LIST_REQUEST = 'GET_BOOKING_LIST_REQUEST';
export const GET_BOOKING_LIST_SUCCESS = 'GET_BOOKING_LIST_SUCCESS';
export const GET_BOOKING_LIST_FAILURE = 'GET_BOOKING_LIST_FAILURE';

// export const GET_VESSAL_REQUEST = 'GET_VESSAL_REQUEST';
// export const GET_VESSAL_SUCCESS = 'GET_VESSAL_SUCCESS';
// export const GET_VESSAL_FAILURE = 'GET_VESSAL_FAILURE';



export const GET_INVOICEBILL_REQUEST = 'GET_INVOICEBILL_REQUEST';
export const GET_INVOICEBILL_SUCCESS = 'GET_INVOICEBILL_SUCCESS';
export const GET_INVOICEBILL_FAILURE = 'GET_INVOICEBILL_FAILURE';

// export const FETCH_INVOICE_TABLE_REQUEST = "FETCH_INVOICE_TABLE_REQUEST";
// export const FETCH_INVOICE_TABLE_SUCCESS = "FETCH_INVOICE_TABLE_SUCCESS";
// export const FETCH_INVOICE_TABLE_FAILURE = "FETCH_INVOICE_TABLE_FAILURE";

export const GET_INVOICE_BILL_ID_REQUEST ='GET_INVOICE_BILL_ID_REQUEST';
export const GET_INVOICE_BILL_ID_SUCCESS ='GET_INVOICE_BILL_ID_SUCCESS';
export const GET_INVOICE_BILL_ID_FAILURE ='GET_INVOICE_BILL_ID_FAILURE';

export const CURRENCY_REQUEST = 'CURRENCY_REQUEST';
export const CURRENCY_SUCCESS = 'CURRENCY_SUCCESS';
export const CURRENCY_FAILURE = 'CURRENCY_FAILURE';

export const HEAD_REQUEST = 'HEAD_REQUEST';
export const HEAD_SUCCESS = 'HEAD_SUCCESS';
export const HEAD_FAILURE = 'HEAD_FAILURE';

export const GET_AGENT_SUCCESS = 'GET_AGENT_SUCCESS'
export const GET_AGENT_REQUEST = 'GET_AGENT_REQUEST'
export const GET_AGENT_FAILURE = 'GET_AGENT_FAILURE'

export const BOOKING_AGENT_REQUEST ='BOOKING_AGENT_REQUEST';
export const BOOKING_AGENT_SUCCESS ='BOOKING_AGENT_SUCCESS';
export const BOOKING_AGENT_FAILURE ='BOOKING_AGENT_FAILURE';

export const FETCH_CHARGE_TABLE_REQUEST = 'FETCH_CHARGE_TABLE_REQUEST';
export const FETCH_CHARGE_TABLE_SUCCESS = 'FETCH_CHARGE_TABLE_SUCCESS';
export const FETCH_CHARGE_TABLE_FAILURE = 'FETCH_CHARGE_TABLE_FAILURE';

export const FETCH_CHARGE_NAMES_REQUEST = 'FETCH_CHARGE_NAMES_REQUEST';
export const FETCH_CHARGE_NAMES_SUCCESS = 'FETCH_CHARGE_NAMES_SUCCESS';

export const FETCH_TAX_MASTERS_REQUEST = 'FETCH_TAX_MASTERS_REQUEST';
export const FETCH_TAX_MASTERS_SUCCESS = 'FETCH_TAX_MASTERS_SUCCESS';





