export const GET_BOOKING_LIST_REQUEST = 'GET_BOOKING_LIST_REQUEST';
export const GET_BOOKING_LIST_SUCCESS = 'GET_BOOKING_LIST_SUCCESS';
export const GET_BOOKING_LIST_FAILURE = 'GET_BOOKING_LIST_FAILURE';

// export const GET_VESSAL_REQUEST = 'GET_VESSAL_REQUEST';
// export const GET_VESSAL_SUCCESS = 'GET_VESSAL_SUCCESS';
// export const GET_VESSAL_FAILURE = 'GET_VESSAL_FAILURE';



export const GET_INVOICEBILL_REQUEST = 'GET_INVOICEBILL_REQUEST';
export const GET_INVOICEBILL_SUCCESS = 'GET_INVOICEBILL_SUCCESS';
export const GET_INVOICEBILL_FAILURE = 'GET_INVOICEBILL_FAILURE';

// export const FETCH_INVOICE_TABLE_REQUEST = "FETCH_INVOICE_TABLE_REQUEST";
// export const FETCH_INVOICE_TABLE_SUCCESS = "FETCH_INVOICE_TABLE_SUCCESS";
// export const FETCH_INVOICE_TABLE_FAILURE = "FETCH_INVOICE_TABLE_FAILURE";

export const GET_INVOICE_BILL_ID_REQUEST ='GET_INVOICE_BILL_ID_REQUEST';
export const GET_INVOICE_BILL_ID_SUCCESS ='GET_INVOICE_BILL_ID_SUCCESS';
export const GET_INVOICE_BILL_ID_FAILURE ='GET_INVOICE_BILL_ID_FAILURE';

export const CURRENCY_REQUEST = 'CURRENCY_REQUEST';
export const CURRENCY_SUCCESS = 'CURRENCY_SUCCESS';
export const CURRENCY_FAILURE = 'CURRENCY_FAILURE';


