export const POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_FAILURE = 'POST_LOGIN_FAILURE';

export const ACCESS_CODE_REQUEST = "ACCESS_CODE_REQUEST";
export const ACCESS_CODE_SUCCESS = "ACCESS_CODE_SUCCESS";
export const ACCESS_CODE_FAILURE = "ACCESS_CODE_FAILURE";

export const RESEND_OTP_REQUEST = 'RESEND_OTP_REQUEST';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
export const RESEND_OTP_FAILURE = 'RESEND_OTP_FAILURE';

export const CLEAR_OTP = 'CLEAR_OTP';
export const CLEAR_ACCESSCODE_ERROR = 'CLEAR_ACCESSCODE_ERROR';
export const CLEAR_ACCESSCODE_STATUS = 'CLEAR_ACCESSCODE_STATUS';

