export const POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_FAILURE = 'POST_LOGIN_FAILURE';

export const ACCESS_CODE_REQUEST = "ACCESS_CODE_REQUEST";
export const ACCESS_CODE_SUCCESS = "ACCESS_CODE_SUCCESS";
export const ACCESS_CODE_FAILURE = "ACCESS_CODE_FAILURE";

export const RESEND_OTP_REQUEST = 'RESEND_OTP_REQUEST';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
export const RESEND_OTP_FAILURE = 'RESEND_OTP_FAILURE';

export const CLEAR_OTP = 'CLEAR_OTP';
export const CLEAR_ACCESSCODE_ERROR = 'CLEAR_ACCESSCODE_ERROR';
export const CLEAR_ACCESSCODE_STATUS = 'CLEAR_ACCESSCODE_STATUS';


export const GET_USER_DETAILS_REQUEST = 'GET_USER_DETAILS_REQUEST';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_FAILURE = 'GET_USER_DETAILS_FAILURE';

//Vendor screen page 
export const VENDOR_UPDATE_REQUEST = 'VENDOR_UPDATE_REQUEST';
export const VENDOR_UPDATE_SUCCESS = 'VENDOR_UPDATE_SUCCESS';
export const VENDOR_UPDATE_FAILURE = 'VENDOR_UPDATE_FAILURE';


export const FETCH_COUNTRIES_REQUEST = 'FETCH_COUNTRIES_REQUEST';
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';

export const FETCH_CURRENCIES_REQUEST = 'FETCH_CURRENCIES_REQUEST';
export const FETCH_CURRENCIES_SUCCESS = 'FETCH_CURRENCIES_SUCCESS';

export const FETCH_CITIES_REQUEST = 'FETCH_CITIES_REQUEST';
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';



export const FETCH_VENDOR_BY_ID_REQUEST = 'FETCH_VENDOR_BY_ID_REQUEST';
export const FETCH_VENDOR_BY_ID_SUCCESS = 'FETCH_VENDOR_BY_ID_SUCCESS';
export const FETCH_VENDOR_BY_ID_FAILURE = 'FETCH_VENDOR_BY_ID_FAILURE';


export const UPDATE_VENDOR_BY_ID_REQUEST = 'UPDATE_VENDOR_BY_ID_REQUEST';
export const UPDATE_VENDOR_BY_ID_SUCCESS = 'UPDATE_VENDOR_BY_ID_SUCCESS';
export const UPDATE_VENDOR_BY_ID_FAILURE = 'UPDATE_VENDOR_BY_ID_FAILURE';

export const CREATE_VENDOR_REQUEST = 'CREATE_VENDOR_REQUEST';
export const CREATE_VENDOR_SUCESSS = 'CREATE_VENDOR_SUCCESS';
export const CREATE_VENDOR_FAILURE = 'CREATE_VENDOR_FAILURE';

export const PUT_CONTACT_REQUEST = 'PUT_CONTACT_REQUEST';
export const PUT_CONTACT_SUCCESS = 'PUT_CONTACT_SUCCESS';
export const PUT_CONTACT_FAILURE = 'PUT_CONTACT_FAILURE';


export const DELETE_CONTACT_REQUEST = 'DELETE_CONTACT_REQUEST'
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS'
export const DELETE_CONTACT_FAILURE = 'DELETE_CONTACT_FAILURE'

export const CREATE_CONTACT_REQUEST = 'CREATE_CONTACT_REQUEST';
export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS';
export const CREATE_CONTACT_FAILURE = 'CREATE_CONTACT_FAILURE';

export const FETCH_INACTIVE_VENDORS_REQUEST = 'FETCH_INACTIVE_VENDORS_REQUEST';
export const FETCH_INACTIVE_VENDORS_SUCCESS = 'FETCH_INACTIVE_VENDORS_SUCCESS';
export const FETCH_INACTIVE_VENDORS_FAILURE = 'FETCH_INACTIVE_VENDORS_FAILURE';


export const  MARK_INACTIVE_REQUEST = 'MARK_INACTIVE_REQUEST';
export const  MARK_INACTIVE_SUCCESS = 'MARK_INACTIVE_SUCCESS';
export const  MARK_INACTIVE_FAILURE = 'MARK_INACTIVE_FAILURE';

export const  MARK_ACTIVE_REQUEST = 'MARK_ACTIVE_REQUEST';
export const  MARK_ACTIVE_SUCCESS = 'MARK_ACTIVE_SUCCESS';
export const  MARK_ACTIVE_FAILURE = 'MARK_ACTIVE_FAILURE';

export const GET_BOOKING_LIST_REQUEST = 'GET_BOOKING_LIST_REQUEST';
export const GET_BOOKING_LIST_SUCCESS = 'GET_BOOKING_LIST_SUCCESS';
export const GET_BOOKING_LIST_FAILURE = 'GET_BOOKING_LIST_FAILURE';











